import type { Metadata } from "next";
import "./globals.css";
import LayoutWrapper from "@/Components/LayoutWrapper";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body data-new-gr-c-s-check-loaded="14.1247.0" data-gr-ext-installed="">
        <LayoutWrapper>{children}</LayoutWrapper>
      </body>
    </html>
  );
}
